[theme]
primaryColor='#529AEF'
backgroundColor='#F1F5FB'
secondaryBackgroundColor='#FFFFFF'
textColor='#252733'
font='sans serif'

[global]
dataFrameSerialization = 'legacy'

[server]
headless = true
port = $PORT
enableCORS = false